'use client';
import { useEffect, useMemo, useState } from 'react';
import { Code2, Equal, ListOrdered, Loader2, Music2, Play, Plus, RotateCcw, Save, SlidersHorizontal, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Slider } from '@/components/ui/slider';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from '@/components/ui/empty';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { FEATURES, formulaFromRules, selectTracks, type Algorithm, type Feature, type ListeningSettings, type Selection } from '@/lib/algorithm';
import type { Track } from '@/lib/music';

export function AlgorithmEditor({ tracks, settings, onSave, onPlay, onImport }: { tracks: Track[]; settings: ListeningSettings; onSave: (settings: ListeningSettings) => Promise<boolean>; onPlay: (selection: Selection[]) => void; onImport: () => void }) {
  const [draft, setDraft] = useState<Algorithm>(settings.algorithm), [saving, setSaving] = useState(false);
  useEffect(() => setDraft(settings.algorithm), [settings.algorithm]);
  const preview = useMemo(() => { try { return { rows: selectTracks(tracks, { mode: 'custom', algorithm: draft }, 7291), error: '' }; } catch (error) { return { rows: [] as Selection[], error: error instanceof Error ? error.message : 'Controlla le regole.' }; } }, [draft, tracks]);
  const dirty = JSON.stringify(draft) !== JSON.stringify(settings.algorithm);
  async function save() { if (preview.error || saving) return; setSaving(true); const ok = await onSave({ mode: 'custom', algorithm: { ...draft, name: draft.name.trim() } }); setSaving(false); if (ok) toast.success('Algoritmo salvato e attivato.'); }
  function addRule() { const feature = (Object.keys(FEATURES) as Feature[]).find(f => !draft.rules.some(r => r.feature === f)) || 'casuale'; setDraft({ ...draft, rules: [...draft.rules, { id: crypto.randomUUID(), feature, weight: 1 }] }); }
  return <div className="algorithm-workspace"><div className="algorithm-editor-panel"><div className="algorithm-name"><label htmlFor="algorithm-name">Nome del tuo algoritmo</label><Input id="algorithm-name" maxLength={60} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /><span className={dirty ? 'draft-status unsaved' : 'draft-status'}>{dirty ? 'Modifiche da salvare' : settings.mode === 'custom' ? 'Salvato · in uso' : 'Salvato · modalità casuale attiva'}</span></div>
    <Tabs value={draft.method} onValueChange={method => setDraft({ ...draft, method: method as Algorithm['method'] })}><TabsList className="algorithm-tabs"><TabsTrigger value="rules"><SlidersHorizontal size={16} />Regole e pesi</TabsTrigger><TabsTrigger value="formula"><Code2 size={16} />Formula</TabsTrigger></TabsList>
      <TabsContent value="rules"><p className="algorithm-help">Scegli cosa conta. Un peso positivo favorisce il criterio; uno negativo lo penalizza. I contributi si sommano.</p><div className="algorithm-rules">{draft.rules.map((rule, index) => <div className="algorithm-rule" key={rule.id}><div className="rule-top"><span className="rule-index">{String(index + 1).padStart(2, '0')}</span><Select value={rule.feature} onValueChange={value => setDraft({ ...draft, rules: draft.rules.map(r => r.id === rule.id ? { ...r, feature: value as Feature } : r) })}><SelectTrigger aria-label={`Criterio della regola ${index + 1}`}><SelectValue /></SelectTrigger><SelectContent>{Object.entries(FEATURES).map(([value, f]) => <SelectItem value={value} key={value}>{f.label}</SelectItem>)}</SelectContent></Select><button className="icon-button" aria-label={`Rimuovi regola ${index + 1}`} onClick={() => setDraft({ ...draft, rules: draft.rules.filter(r => r.id !== rule.id) })}><Trash2 size={17} /></button></div><p>{FEATURES[rule.feature].description}</p><div className="rule-weight"><span>Peso</span><Slider aria-label={`Peso: ${FEATURES[rule.feature].label}`} min={-10} max={10} step={0.5} value={[rule.weight]} onValueChange={v => setDraft({ ...draft, rules: draft.rules.map(r => r.id === rule.id ? { ...r, weight: v[0] } : r) })} /><output className={rule.weight < 0 ? 'negative-weight' : 'positive-weight'}>{rule.weight > 0 ? '+' : ''}{rule.weight}</output></div></div>)}</div><div className="rule-buttons"><button className="button outline" disabled={draft.rules.length >= 20} onClick={addRule}><Plus size={17} />Aggiungi una regola</button><button className="text-button" onClick={() => setDraft({ ...draft, rules: [] })}><RotateCcw size={15} />Riparti da zero</button></div></TabsContent>
      <TabsContent value="formula"><p className="algorithm-help">Scrivi il punteggio di un brano. Il valore più alto viene riprodotto prima. La formula può usare i tuoi dati locali e le funzioni qui sotto.</p><label className="formula-label" htmlFor="algorithm-formula">Punteggio =</label><Textarea id="algorithm-formula" className="formula-input" value={draft.formula} onChange={e => setDraft({ ...draft, formula: e.target.value })} maxLength={600} spellCheck={false} rows={5} aria-invalid={!!preview.error} /><div className="formula-tools"><button className="text-button" onClick={() => setDraft({ ...draft, formula: formulaFromRules(draft.rules) })}><Equal size={16} />Usa la formula delle regole</button><small>{draft.formula.length}/600</small></div><p className="formula-functions"><code>+ − * / ^ ( )</code><br /><code>min(a,b) · max(a,b) · abs(x) · sqrt(x) · log(x) · floor(x)</code></p><div className="variable-list"><h3>Le tue variabili</h3>{Object.entries(FEATURES).map(([key, f]) => <button key={key} onClick={() => setDraft({ ...draft, formula: `${draft.formula} ${key}`.slice(0, 600) })} title={`Inserisci ${key}`}><code>{key}</code><span>{f.description}</span><Plus size={14} /></button>)}</div></TabsContent>
    </Tabs>{preview.error && <p role="alert" className="formula-error">{preview.error}</p>}<div className="algorithm-save"><span>Le tue regole restano su questo dispositivo.</span><button className="button primary" disabled={saving || !!preview.error} onClick={() => void save()}>{saving ? <Loader2 size={17} className="spin" /> : <Save size={17} />}{saving ? 'Salvataggio…' : 'Salva e attiva'}</button></div></div>
    <aside className="algorithm-preview"><div className="preview-heading"><ListOrdered size={22} /><div><h2>Il risultato, in anteprima</h2><p>Si aggiorna mentre cambi le regole.</p></div></div>{preview.rows.length ? <><Table className="score-table"><TableHeader><TableRow><TableHead>BRANO</TableHead><TableHead>PUNTI</TableHead></TableRow></TableHeader><TableBody>{preview.rows.slice(0, 6).map((item, i) => <TableRow key={item.track.id}><TableCell><div className="score-track"><span>{i + 1}</span><div><strong>{item.track.title}</strong><small>{item.track.artist}</small></div></div></TableCell><TableCell className="score-value">{Number(item.score!.toFixed(2))}</TableCell></TableRow>)}</TableBody></Table><p className="score-explanation">Si usa solo il punteggio che hai definito. A parità di punti, l’ordine è casuale.</p><button className="button outline" onClick={() => onPlay(preview.rows)}><Play size={16} />Ascolta questa anteprima</button></> : <Empty className="preview-empty"><Music2 size={31} /><EmptyHeader><EmptyTitle>{preview.error ? 'Controlla il tuo algoritmo' : 'Porta qui la tua musica'}</EmptyTitle><EmptyDescription>{preview.error ? 'Correggi l’errore per rivedere la selezione.' : 'Vedrai come le tue regole ordinano i brani reali della libreria.'}</EmptyDescription></EmptyHeader>{!preview.error && <button className="button outline" onClick={onImport}><Plus size={16} />Importa musica</button>}</Empty>}<div className="algorithm-example"><span className="eyebrow">UN ESEMPIO PER PARTIRE</span><code>preferito * 5 - salti * 2</code><p>+5 punti ai preferiti, −2 per ogni salto. Poi puoi aggiungere tutte le sfumature che vuoi.</p></div></aside>
  </div>;
}
